//
//  OrangeView.swift
//  Bridge_Example
//
//  Created by Alexey Pichukov on 27/09/2019.
//  Copyright © 2019 CocoaPods. All rights reserved.
//

import UIKit
import Bridge

class OrangeView: UIView {

    @IBOutlet weak var countLabel: UILabel!
    let bridgeNode: BridgeNode<EntityType>? = BridgeNode<EntityType>(withAddress: BridgeNodeAddress<EntityType>(withAutogeneratedIdAndType: .orange))

    func initBridge() {
        bridgeNode?.add(delegate: self)
    }
    
    @IBAction func changePinkButtonAction(_ sender: Any) {
        let message = BridgeMessage<EntityType>(fromSourse: bridgeNode!.address,
                                                toDestination: BridgeNodeAddress<EntityType>(withOnlyType: .pink),
                                                withValue: "Reset From Orange")
        bridgeNode!.send(message: message)
    }
    
    @IBAction func groupButtonAction(_ sender: Any) {
        let message = BridgeMessage<EntityType>(fromSourse: bridgeNode!.address,
                                                toDestination: BridgeNodeAddress<EntityType>(withOnlyType: .general),
                                                withValue: UIColor.random)
        bridgeNode!.send(message: message)
    }
}

extension OrangeView: BridgeNodeConnectable {}

extension OrangeView: BridgeCallable {
    
    func recieve<EntityType>(message: BridgeMessage<EntityType>) {
        guard let count = message.value as? String else { return }
        countLabel.text = count
    }
    
}
