//
//  PinkView.swift
//  Bridge_Example
//
//  Created by Alexey Pichukov on 27/09/2019.
//  Copyright © 2019 CocoaPods. All rights reserved.
//

import UIKit
import Bridge

class PinkView: UIView {

    @IBOutlet weak var countLabel: UILabel!
    let bridgeNode: BridgeNode<EntityType>? = BridgeNode<EntityType>(withAddress: BridgeNodeAddress<EntityType>(withAutogeneratedIdAndType: .pink))

    func initBridge() {
        bridgeNode?.add(delegate: self)
    }
    
    @IBAction func changeOrarngeButtonAction(_ sender: Any) {
        let message = BridgeMessage<EntityType>(fromSourse: bridgeNode!.address,
                                                toDestination: BridgeNodeAddress<EntityType>(withOnlyType: .orange),
                                                withValue: "Reset From Pink")
        bridgeNode!.send(message: message)
    }
    
    @IBAction func groupButtonAction(_ sender: Any) {
        let message = BridgeMessage<EntityType>(fromSourse: bridgeNode!.address,
                                                toDestination: BridgeNodeAddress<EntityType>(withOnlyType: .general),
                                                withValue: UIColor.random)
        bridgeNode!.send(message: message)
    }
}

extension PinkView: BridgeNodeConnectable {}

extension PinkView: BridgeCallable {
    
    func recieve<EntityType>(message: BridgeMessage<EntityType>) {
        guard let count = message.value as? String else { return }
        countLabel.text = count
    }
    
}
